apiVersion: batch/v1
kind: Job
metadata:
  name: lobsters-db-seed
spec:
        #selector:
        #matchLabels:
        #task: db-seed
  template:
    metadata:
      name: lobsters-db-seed
      labels:
        task: db-seed
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:testing
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
          command:
            - "/usr/local/bundle/bin/rake"
            - "db:seed"
      restartPolicy: Never
